"""create users and routines tables

Revision ID: 40708b00e628
Revises: 
Create Date: 2026-04-23 14:55:20.355619

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '40708b00e628'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('moment', sa.String(), nullable=True),
    sa.Column('niveau', sa.String(), nullable=True),
    sa.Column('profil_cible', sa.String(), nullable=True),
    sa.Column('humeur_declencheur', sa.String(), nullable=True),
    sa.Column('etapes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('objectif', sa.String(), nullable=True),
    sa.Column('profil_vie', sa.String(), nullable=True),
    sa.Column('disponibilite', sa.Integer(), nullable=True),
    sa.Column('heure_rappel', sa.Time(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('routines')
    # ### end Alembic commands ### 