"""add humeur_declencheur to routines

Revision ID: e4d382cd0d72
Revises: 40708b00e628
Create Date: 2026-05-28 10:10:23.966143

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e4d382cd0d72'
down_revision: Union[str, None] = '40708b00e628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_routines_categorie'), 'routines', ['categorie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routines_categorie'), table_name='routines')
    # ### end Alembic commands ### 